<?php

namespace AppBundle\Repository;

use AppBundle\Entity\City;
use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
    /**
     * Save entity.
     *
     * @param City $city City entity
     */
    public function save(City $city)
    {
        $this->_em->persist($city);
        $this->_em->flush();
    }

    /**
     * Delete entity.
     *
     * @param City $city City entity
     */
    public function delete(City $city)
    {
        $this->_em->remove($city);
        $this->_em->flush();
    }
}
