<?php
/**
 * Baza zawodów.
 *
 * @author Dominika Skoczeń <doskoczen@gmail.com>
 */
namespace AppBundle\Repository;

use AppBundle\Entity\Competition;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * CompetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetitionRepository extends EntityRepository
{
    /**
     * Save entity.
     *
     * @param Competition $competition Competition entity
     */
    public function save(Competition $competition)
    {
        $this->_em->persist($competition);
        $this->_em->flush();
    }

    /**
     * Delete entity.
     *
     * @param Competition $competition Competition entity
     */
    public function delete(Competition $competition)
    {
        $this->_em->remove($competition);
        $this->_em->flush();
    }

    /**
     * Gets all records paginated.
     *
     * @param int $page Page number
     *
     * @return \Pagerfanta\Pagerfanta Result
     */
    public function findAllPaginated($page = 1)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryAll(), false));
        $paginator->setMaxPerPage(Competition::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }

    /**
     * Query all entities.
     *
     * @return \Doctrine\ORM\Query
     */
    protected function queryAll()
    {
        $qb = $this->createQueryBuilder('b');
        $qb->select('b')
            ->orderBy('b.date', 'DESC');

        return $qb;
    }
}
