<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Contestant;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * ContestantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContestantRepository extends EntityRepository
{
    /**
     * Save entity.
     *
     * @param Contestant $contestant Contestant entity
     */
    public function save(Contestant $contestant)
    {
        $this->_em->persist($contestant);
        $this->_em->flush();
    }

    /**
     * Delete entity.
     *
     * @param Contestant $contestant Contestant entity
     */
    public function delete(Contestant $contestant)
    {
        $this->_em->remove($contestant);
        $this->_em->flush();
    }

    /**
     * Gets all records paginated.
     *
     * @param int $page Page number
     *
     * @return \Pagerfanta\Pagerfanta Result
     */
    public function findAllPaginated($page = 1)
    {
        $paginator = new Pagerfanta(new DoctrineORMAdapter($this->queryAll(), false));
        $paginator->setMaxPerPage(Contestant::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;
    }

    /**
     * Query all entities.
     *
     * @return \Doctrine\ORM\Query
     */
    protected function queryAll()
    {
        $qb = $this->createQueryBuilder('b');
        $qb->select('b')
            ->orderBy('b.surname', 'ASC');

        return $qb;
    }

    /**
     * Gets contestants by sex.
     *
     * @param string $sex Sex
     *
     * @param integer $page Page number
     *
     * @return \Doctrine\ORM\Query
     */
    public function findBySexPaginated($sex, $page = 1)
    {
        $qb = $this->createQueryBuilder('b');
        $qb->select('b')
            ->where('b.sex = :sex')
            ->setParameter(':sex', $sex);

        $paginator = new Pagerfanta(new DoctrineORMAdapter($qb, false));
        $paginator->setMaxPerPage(Contestant::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;

    }

    /**
     * Gets contestants alphabetically reversed and paginate.
     *
     *
     * @param integer $page Page number
     *
     * @return \Doctrine\ORM\Query
     */
    public function findAllAphabeticallyReversedPaginated($page = 1)
    {
        $qb = $this->createQueryBuilder('b');
        $qb->select('b')
            ->orderBy('b.surname', 'DESC');

        $paginator = new Pagerfanta(new DoctrineORMAdapter($qb, false));
        $paginator->setMaxPerPage(Contestant::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;

    }

    /**
     * Gets contestants by sex alphabetically reversed and paginate.
     *
     * @param string $sex Sex
     *
     * @param integer $page Page number
     *
     * @return \Doctrine\ORM\Query
     */
    public function findAllBySexAphabeticallyReversedPaginated($sex, $page = 1)
    {
        $qb = $this->createQueryBuilder('b');
        $qb->select('b')
            ->where('b.sex = :sex')
            ->setParameter(':sex', $sex)
            ->orderBy('b.surname', 'DESC');

        $paginator = new Pagerfanta(new DoctrineORMAdapter($qb, false));
        $paginator->setMaxPerPage(Contestant::NUM_ITEMS);
        $paginator->setCurrentPage($page);

        return $paginator;

    }



}
