<?php

namespace AppBundle\Repository;

use AppBundle\Entity\School;
use Doctrine\ORM\EntityRepository;

/**
 * SchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolRepository extends EntityRepository
{
    /**
     * Save entity.
     *
     * @param School $school School entity
     */
    public function save(School $school)
    {
        $this->_em->persist($school);
        $this->_em->flush();
    }

    /**
     * Delete entity.
     *
     * @param School $school School entity
     */
    public function delete(School $school)
    {
        $this->_em->remove($school);
        $this->_em->flush();
    }
}
